// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: sdcs_grpc/sdcs.proto

package sdcs_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NodeId int32  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *SetIndexReq) Reset() {
	*x = SetIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIndexReq) ProtoMessage() {}

func (x *SetIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIndexReq.ProtoReflect.Descriptor instead.
func (*SetIndexReq) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{0}
}

func (x *SetIndexReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetIndexReq) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SetIndexRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *SetIndexRep) Reset() {
	*x = SetIndexRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIndexRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIndexRep) ProtoMessage() {}

func (x *SetIndexRep) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIndexRep.ProtoReflect.Descriptor instead.
func (*SetIndexRep) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{1}
}

func (x *SetIndexRep) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type SetDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetDataReq) Reset() {
	*x = SetDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDataReq) ProtoMessage() {}

func (x *SetDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDataReq.ProtoReflect.Descriptor instead.
func (*SetDataReq) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{2}
}

func (x *SetDataReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetDataReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetDataRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *SetDataRep) Reset() {
	*x = SetDataRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDataRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDataRep) ProtoMessage() {}

func (x *SetDataRep) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDataRep.ProtoReflect.Descriptor instead.
func (*SetDataRep) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{3}
}

func (x *SetDataRep) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type GetDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetDataReq) Reset() {
	*x = GetDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataReq) ProtoMessage() {}

func (x *GetDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataReq.ProtoReflect.Descriptor instead.
func (*GetDataReq) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{4}
}

func (x *GetDataReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetDataRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val    string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	NodeId int32  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Res    bool   `protobuf:"varint,3,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *GetDataRep) Reset() {
	*x = GetDataRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRep) ProtoMessage() {}

func (x *GetDataRep) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRep.ProtoReflect.Descriptor instead.
func (*GetDataRep) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataRep) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *GetDataRep) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *GetDataRep) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type DeleteIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteIndexReq) Reset() {
	*x = DeleteIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexReq) ProtoMessage() {}

func (x *DeleteIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexReq.ProtoReflect.Descriptor instead.
func (*DeleteIndexReq) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteIndexReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteIndexRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *DeleteIndexRep) Reset() {
	*x = DeleteIndexRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdcs_grpc_sdcs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIndexRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRep) ProtoMessage() {}

func (x *DeleteIndexRep) ProtoReflect() protoreflect.Message {
	mi := &file_sdcs_grpc_sdcs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRep.ProtoReflect.Descriptor instead.
func (*DeleteIndexRep) Descriptor() ([]byte, []int) {
	return file_sdcs_grpc_sdcs_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIndexRep) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

var File_sdcs_grpc_sdcs_proto protoreflect.FileDescriptor

var file_sdcs_grpc_sdcs_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x64, 0x63, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x38, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x1e,
	0x0a, 0x0a, 0x53, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x1e,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x49,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x22, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65,
	0x73, 0x32, 0x86, 0x02, 0x0a, 0x09, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x12,
	0x3c, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x2e, 0x73, 0x64,
	0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x07, 0x53, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x2e, 0x73, 0x64, 0x63, 0x73, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x15, 0x2e, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x73, 0x64, 0x63,
	0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x70, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x19, 0x2e, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x73, 0x64, 0x63, 0x73, 0x2f, 0x73, 0x64, 0x63, 0x73, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdcs_grpc_sdcs_proto_rawDescOnce sync.Once
	file_sdcs_grpc_sdcs_proto_rawDescData = file_sdcs_grpc_sdcs_proto_rawDesc
)

func file_sdcs_grpc_sdcs_proto_rawDescGZIP() []byte {
	file_sdcs_grpc_sdcs_proto_rawDescOnce.Do(func() {
		file_sdcs_grpc_sdcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdcs_grpc_sdcs_proto_rawDescData)
	})
	return file_sdcs_grpc_sdcs_proto_rawDescData
}

var file_sdcs_grpc_sdcs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sdcs_grpc_sdcs_proto_goTypes = []interface{}{
	(*SetIndexReq)(nil),    // 0: sdcs_grpc.SetIndexReq
	(*SetIndexRep)(nil),    // 1: sdcs_grpc.SetIndexRep
	(*SetDataReq)(nil),     // 2: sdcs_grpc.SetDataReq
	(*SetDataRep)(nil),     // 3: sdcs_grpc.SetDataRep
	(*GetDataReq)(nil),     // 4: sdcs_grpc.GetDataReq
	(*GetDataRep)(nil),     // 5: sdcs_grpc.GetDataRep
	(*DeleteIndexReq)(nil), // 6: sdcs_grpc.DeleteIndexReq
	(*DeleteIndexRep)(nil), // 7: sdcs_grpc.DeleteIndexRep
}
var file_sdcs_grpc_sdcs_proto_depIdxs = []int32{
	0, // 0: sdcs_grpc.sdcs_sync.SetIndex:input_type -> sdcs_grpc.SetIndexReq
	2, // 1: sdcs_grpc.sdcs_sync.SetData:input_type -> sdcs_grpc.SetDataReq
	4, // 2: sdcs_grpc.sdcs_sync.GetData:input_type -> sdcs_grpc.GetDataReq
	6, // 3: sdcs_grpc.sdcs_sync.DeleteIndex:input_type -> sdcs_grpc.DeleteIndexReq
	1, // 4: sdcs_grpc.sdcs_sync.SetIndex:output_type -> sdcs_grpc.SetIndexRep
	3, // 5: sdcs_grpc.sdcs_sync.SetData:output_type -> sdcs_grpc.SetDataRep
	5, // 6: sdcs_grpc.sdcs_sync.GetData:output_type -> sdcs_grpc.GetDataRep
	7, // 7: sdcs_grpc.sdcs_sync.DeleteIndex:output_type -> sdcs_grpc.DeleteIndexRep
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdcs_grpc_sdcs_proto_init() }
func file_sdcs_grpc_sdcs_proto_init() {
	if File_sdcs_grpc_sdcs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdcs_grpc_sdcs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIndexRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDataRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdcs_grpc_sdcs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIndexRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdcs_grpc_sdcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdcs_grpc_sdcs_proto_goTypes,
		DependencyIndexes: file_sdcs_grpc_sdcs_proto_depIdxs,
		MessageInfos:      file_sdcs_grpc_sdcs_proto_msgTypes,
	}.Build()
	File_sdcs_grpc_sdcs_proto = out.File
	file_sdcs_grpc_sdcs_proto_rawDesc = nil
	file_sdcs_grpc_sdcs_proto_goTypes = nil
	file_sdcs_grpc_sdcs_proto_depIdxs = nil
}
