services:
  server1:
    build: .
    command: /root/sdcs 0
    network_mode: host
  server2:
    build: .
    command: /root/sdcs 1
    network_mode: host
  server3:
    build: .
    command: /root/sdcs 2
    network_mode: host
