SRC_FILE=" lockfree_queue.c"
SRC_FILE+=" test.c"

INCLUDE_PATH="./include"

RANDOM_FILE_BLOCKSIZE="1M"
RANDOM_FILE_BLOCKCOUNT="1024"
RANDOM_FILE_NAME="input"
OUTPUT_FILE_NAME="output"

CONSUMERS_COUNT=2

dd if=/dev/urandom of=${RANDOM_FILE_NAME} bs=${RANDOM_FILE_BLOCKSIZE} count=${RANDOM_FILE_BLOCKCOUNT}
gcc -O3 ${SRC_FILE} -I${INCLUDE_PATH} -lpthread
sleep 1
time ./a.out ${CONSUMERS_COUNT} ${RANDOM_FILE_NAME} ${OUTPUT_FILE_NAME}

INPUT_MD5SUM=$(md5sum ${RANDOM_FILE_NAME})
OUTPUT_MD5SUM=$(md5sum ${OUTPUT_FILE_NAME})
echo "INPUT_MD5SUM:${INPUT_MD5SUM}"
echo "OUTPUT_MD5SUM:${OUTPUT_MD5SUM}"

sleep 1
rm -rf ${RANDOM_FILE_NAME} ${OUTPUT_FILE_NAME} ./a.out